import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ThemeContextProvider from '@/context/ThemeContextProvider'
import { Sidebar } from '@/components/navigation/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: `Bramsurya's Portfolio Website`,
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} bg-primaryLightBg dark:bg-primaryDarkBg`}
			>
				<ThemeContextProvider>
					<Sidebar>{children}</Sidebar>
				</ThemeContextProvider>
			</body>
		</html>
	)
}
