import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Sidebar } from '@/components/navigation/Sidebar'
import { ThemeProvider } from 'next-themes'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: `Bramsurya's Portfolio Website`,
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.className} h-dvh`}>
				<ThemeProvider attribute='class'>
					<Sidebar>{children}</Sidebar>
				</ThemeProvider>
			</body>
		</html>
	)
}
