import type { Metadata } from 'next'
import { Sidebar } from '@/components/navigation/Sidebar'

export const metadata: Metadata = {
	title: `Bramsurya's Portfolio Website`,
	description: 'Generated by create next app',
}

export default function MainLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return <Sidebar>{children}</Sidebar>
}
